### PR TITLE
GNMI Get sync to honor the requested encoding

### PR DESCRIPTION
**Pull request by steiler**
propagate the requested encoding all the way down to gnmic

### CODE REVIEW

**Comment by henderiw** [comment]
dont we need to remove  this as well ?

func (t *gnmiTarget) Get(ctx context.Context, req *sdcpb.GetDataRequest) (*sdcpb.GetDataResponse, error) {
	var err error
	gnmiReq := &gnmi.GetRequest{
		Path:     make([]*gnmi.Path, 0, len(req.GetPath())),
	==>>	Encoding: gnmi.Encoding_ASCII,
	}
	for _, p := range req.GetPath() {
		gnmiReq.Path = append(gnmiReq.Path, utils.ToGNMIPath(p))
	}

**Comment by henderiw** [comment]
is it not better to remove this ASCII default as it is always overwritten

	gnmiReq := &gnmi.GetRequest{
		Path:     make([]*gnmi.Path, 0, len(req.GetPath())),
		Encoding: gnmi.Encoding_ASCII,
	}
	for _, p := range req.GetPath() {
		gnmiReq.Path = append(gnmiReq.Path, utils.ToGNMIPath(p))
	}

**Comment by steiler** [comment]
@henderiw see the update

**Review by henderiw — APPROVED** [review]
lgtm

**Review by henderiw — COMMENTED** [review]
what does not work is ASCII as this is not mapped. 

Configserver uses these.

const (
	Encoding_UNKNOWN   Encoding = "UNKNOWN"
	Encoding_JSON      Encoding = "JSON"
	Encoding_JSON_IETF Encoding = "JSON_IETF"
	Encoding_BYTES     Encoding = "BYTES"
	Encoding_PROTO     Encoding = "PROTO"
	Encoding_ASCII     Encoding = "ASCII"
	Encoding_CONFIG    Encoding = "CONFIG"
)

**Pull request closed without merging**
