### PR TITLE
XML Key Ordering, missing namespaces, decimal conversion additions

### PR DESCRIPTION
**Pull request by alexandernorth**
This PR includes several fixes:
- (legacy) fixes to netconf xml generation pre-tree
- Added sort option to tree XML generation to order tree based on schema keys (options: None, Alphabetical, SchemaBound)

### CODE REVIEW

**Comment by steiler** [comment]
Thanks Alex!
Can I ask what the purpose for the SchemaBound ordering is? Unfortunately I do not understand it. Thanks

**Comment by alexandernorth** [comment]
Of course, it came from the requirement that our NF seems to require list elements with a key defined to have the first children in the order defined in that key, which may not be the alphabetical order. 
for example, given the following Yang model:
```
list a {
    key “id”;
    leaf id {}
    leaf abc {}
  }
```
In the current sort implementation, abc would be the first child and before id which would cause the config to be rejected by the NF. 

This PR actually should depend on https://github.com/sdcio/schema-server/pull/134 which fixes the order of the keys sent by the schema-server to match the order given in the Yang model.

**Comment by steiler** [comment]
You seem to be totally right... 

> Key elements must be the first elements within the list entry to comply with the YANG and NETCONF standards.
we were also discussing if we should add more option flags or simply go with the sorted output... now also given this, I tend to do so.
The other discussion point was to also take data types into account and sort not just in alphabetical (string) order.
So if you like and have the time, give it a shot maybe.

**Comment by hansthienpondt** [comment]
```==============================================================================
02-Crud                                                               | PASS |
117 tests, 117 passed, 0 failed
==============================================================================```

i will approve schema-server and bump the version; then will update this PR with the adjusted version

**Review by hansthienpondt — APPROVED** [review]
LGTM

**Pull request merged**
